# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: s3 sync
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME : '13th'
  AWS_REGION : 'eu-west-1'
  PROJECT_PATH: './'
# permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::832823214476:role/s3_cloudfront_access
          role-session-name: s3-sync-and-invalidate-cache
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  sync all to s3 and invalidate cloudfront cache
        working-directory: ./
        run: |
          aws s3 sync ./ s3://${{ env.BUCKET_NAME }}/ 
          aws cloudfront create-invalidation --distribution-id E2MD18IJX7JWHR --paths '/*'
